<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <?php
    $static = new Common_GetStatic();
    $static->getStaticUrl('easyui_mobile');
    ?>
    <style>
        .header-img {
            width:15%;
            max-width:50px;
            height:50px;
        }
        .left {
            float: left;
        }
        .info{
            margin-left: 5%;
            margin-top: 8px;
        }
        .username {
            width:13%;
            font-size: 16px;
            font-family: "黑体";
        }
        .line {
            width:15%;
            padding-right: 10px;
            border-right: 1px solid silver;
        }
        .content {
            width: 55%;
            display:block;
            word-break: break-all;
            word-wrap: break-word;
            white-space:normal;
            overflow:hidden;
        }
        .comment {
            width: 90%;
            max-width:50px;
        }
    </style>
</head>
<body>
<div class="easyui-navpanel">
    <ul id="list">
        <?php
        foreach ($thingList as $list) { ?>
        <li value="<?=$list['thing_id']?>">
            <img class="header-img left" src="<?php echo $static->getImg('nohead.png')?>">
            <div class="left info line">
                <span class="username"><?=$list['user_name']?></span><br/>
                <span class="m-badge c2 comment">评论：<?=$list['num']?></span>
            </div>
            <div class="left info content">
                <?=$list['thing_content']?>
            </div>
        </li>
        <?php } ?>
    </ul>
</div>
<iframe id="p2" class="easyui-navpanel"></iframe>
</body>
</html>
<script type="text/javascript">
    $(function(){
        $("#list").datalist({
            fit: true,
            lines: true,
            border: false,
            textFormatter: function(value){
                return '<a href\'javascript:void(0)\' class=\'datalist-link\'>' + value + '</a>';
            },
            onClickRow: function(index,row){
                var thing_id =  row.value;
                $("#p2").attr("src","/app_comments/showCommentsList?thing_id="+thing_id);
                $.mobile.go('#p2');
            }
        });
    })
</script>