<!doctype html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <title>Basic Accordion - jQuery EasyUI Mobile Demo</title>
    <?php
    $static = new Common_GetStatic();
    $static->getStaticUrl('easyui_mobile');
    $static->getStaticUrl('js','myinfo.js');
    ?>
</head>
<body>
<div class="easyui-navpanel">
    <div class="easyui-accordion" fit="true" border="false">
        <div title="个人资料">
            <ul class="m-list">
                <li>昵称:<span style="color: #919191"><?=$userInfo['user_name']?></span>
                    <div class="m-right">
                        <a id="user_name" class="easyui-linkbutton">点击修改</a>
                    </div>
                </li>
                <li>性别:<span style="color: #919191"><?=$userInfo['user_sex']?></span>
                    <div class="m-right">
                        <a id="user_sex" class="easyui-linkbutton">点击修改</a>
                    </div>
                </li>
                <li>头像:
                    <div class="m-right">
                        <a id="user_head" class="easyui-linkbutton">点击修改</a>
                    </div>
                </li>
                <li>邮箱:<span style="color: #919191"><?=$userInfo['user_email']?></span>
                    <div class="m-right">
                        <a id="user_email" class="easyui-linkbutton">点击修改</a>
                    </div>
                </li>
            </ul>
        </div>
        <div title="我的观点">
            <ul class="m-list">
                <li>发表观点:
                    <div class="m-right">
                        <a id="addThingBtn" class="easyui-linkbutton">点击发表</a>
                    </div>
                </li>
            </ul>

            <ul class="m-list" id="list">

                <?php if(empty($myThingList)) { ?>
                    <div style="margin: 10px; text-align: center; color: #919191">
                        你还没有发表观点，快去发表吧~！
                    </div>
                <?php } else {
                foreach ($myThingList as $row) { ?>
                    <li value="<?=$row['thing_id']?>">
                        <?=$row['thing_content']?>
                        <span class="m-badge" style="float:right">
                            <?php if($row['thing_pass'] == 1) {
                                 echo $row['comments_num'];
                            } else {
                                echo "未通过";
                            } ?>
                        </span>
                    </li>
                <?php }
                } ?>

            </ul>
        </div>
    </div>
</div>

<div id="change" class="easyui-dialog" style="padding:20px 6px;width:80%;">
    <div style="margin-bottom:10px">
        <input class="easyui-textbox text inputval" style="width:100%;height:30px">
    </div>
    <div class="dialog-button" style="text-align: center;">
        <a class="easyui-linkbutton update" style="width:40%;height:35px">确定</a>
        <a class="easyui-linkbutton" style="width:40%;height:35px" onclick="$('#change').dialog('close')">取消</a>
    </div>
</div>

<div id="changeSex" class="easyui-dialog" style="padding:20px 6px;width:80%;">
    <div style="margin-bottom:10px">
        <select id="selectSex" class="easyui-combobox" name="dept" style="width:100%;height:38px" panelHeight="42px">
            <option value="男">男</option>
            <option value="女">女</option>
        </select>
    </div>
    <div class="dialog-button" style="text-align: center;">
            <a class="easyui-linkbutton update" style="width:40%;height:35px">确定</a>
        <a class="easyui-linkbutton" style="width:40%;height:35px" onclick="$('#changeSex').dialog('close')">取消</a>
    </div>
</div>

<div id="addThing" class="easyui-dialog" style="padding:10px 6px;width:80%;">
    <div style="margin-bottom:10px">
        <textarea id="thing_content" rows="3" style="width:98%;"></textarea>
    </div>
    <div class="dialog-button" style="text-align: center;">
        <a id="fb" class="easyui-linkbutton" style="width:40%;height:35px">发表</a>
        <a class="easyui-linkbutton" style="width:40%;height:35px" onclick="$('#addThing').dialog('close')">取消</a>
    </div>
</div>

<iframe id="p2" class="easyui-navpanel"></iframe>
</body>
<script>
        $(function(){
            var thing_id;
            $("#list").datalist({
                fit: true,
                lines: true,
                border: false,
                textFormatter: function(value){
                    return '<a href\'javascript:void(0)\' class=\'datalist-link\'>' + value + '</a>';
                },
                onClickRow: function(index,row){
                    var thing_id =  row.value;
                    $("#p2").attr("src","/app_comments/showCommentsList?thing_id="+thing_id);
                    $.mobile.go('#p2');
                }
            });
        })
</script>
</html>